// src/features/shop/productCatalog.js — Central Product Catalog Registry & Order Tracker
import { db } from "../../firebase";
import { doc, getDoc, collection, addDoc, serverTimestamp } from "firebase/firestore";

// ── COMMON FITNESS & PERFORMANCE PRODUCTS (30 Items) ──
export const COMMON_PRODUCTS = [
  {
    id: "1",
    shopType: "common",
    category: "protein",
    name: "Optimum Nutrition (ON) Gold Standard 100% Whey Protein (Double Rich Chocolate, 2 lbs / 907g)",
    brand: "Optimum Nutrition",
    asin: "B000QSNY54",
    price: "₹3,499",
    originalPrice: "₹4,499",
    discount: "22% OFF",
    image: "/products/1.jpg",
    tags: ["Whey Blend", "24g Protein", "5.5g BCAAs", "Gluten Free", "Labdoor Certified"],
    description: "The world's #1 selling whey protein. 24g pure whey isolate & concentrate blend with 5.5g natural BCAAs per scoop. Fast absorbing post-workout muscle repair.",
    badge: "#1 Best Seller",
    badgeColor: "#f59e0b",
  },
  {
    id: "2",
    shopType: "common",
    category: "protein",
    name: "MuscleBlaze Biozyme Performance Whey (2kg / 4.4 lbs, Rich Chocolate)",
    brand: "MuscleBlaze",
    asin: "B07T48L8H3",
    price: "₹4,799",
    originalPrice: "₹6,299",
    discount: "24% OFF",
    image: "/products/2.jpg",
    tags: ["Enhanced Absorption Formula", "25g Protein", "Clinically Tested", "Zero Bloating"],
    description: "Formulated with patented Enhanced Absorption Formula (EAF) ensuring 50% higher protein absorption and 60% higher BCAA bioavailability for Indian bodies.",
    badge: "Clinical Formula",
    badgeColor: "#3b82f6",
  },
  {
    id: "3",
    shopType: "common",
    category: "protein",
    name: "Dymatize ISO100 Hydrolyzed 100% Whey Protein Isolate (Gourmet Chocolate 2.3kg / 5 lbs)",
    brand: "Dymatize",
    asin: "B009M3M2W6",
    price: "₹8,499",
    originalPrice: "₹11,999",
    discount: "29% OFF",
    image: "/products/3.jpg",
    tags: ["100% Hydrolyzed Isolate", "25g Protein", "<1g Sugar", "Ultra-Fast Absorption"],
    description: "Hydrolyzed whey isolate for instant amino acid flooding into bloodstream. Zero bloating, near zero fat and sugar. Gold standard for competition prep.",
    badge: "Pro Choice",
    badgeColor: "#8b5cf6",
  },
  {
    id: "4",
    shopType: "common",
    category: "creatine",
    name: "Creapure German Micronized Creatine Monohydrate (Unflavoured 250g, 83 Servings)",
    brand: "Creapure® Germany",
    asin: "B079Z7Q8S5",
    price: "₹1,199",
    originalPrice: "₹1,699",
    discount: "30% OFF",
    image: "/products/4.jpg",
    tags: ["99.99% Pure Creapure", "Made in Germany", "Zero DCD/DHT", "Max ATP Output"],
    description: "Manufactured by Alzchem Trostberg GmbH Germany. The purest creatine monohydrate synthesized worldwide. Maximizes muscular phosphocreatine reserves.",
    badge: "Purest Creatine",
    badgeColor: "#10b981",
  },
  {
    id: "5",
    shopType: "common",
    category: "creatine",
    name: "MuscleBlaze Micronized Creatine Monohydrate with CreAMP (100g, Rapid Absorption)",
    brand: "MuscleBlaze",
    asin: "B07T49514G",
    price: "₹549",
    originalPrice: "₹799",
    discount: "31% OFF",
    image: "/products/5.jpg",
    tags: ["Micro-milled", "Unflavoured", "Heavy Lifts", "ATP Energy"],
    description: "Rapid absorption micro-milled particles mix instantly without gritty texture. Delivers immediate cellular hydration and explosive power on bench and squats.",
    badge: "Budget King",
    badgeColor: "#f59e0b",
  },
  {
    id: "6",
    shopType: "common",
    category: "preworkout",
    name: "Cellucor C4 Original Pre-Workout Powder (Fruit Punch, 30 Servings)",
    brand: "Cellucor",
    asin: "B00U464HYK",
    price: "₹2,199",
    originalPrice: "₹2,999",
    discount: "27% OFF",
    image: "/products/6.jpg",
    tags: ["CarnoSyn Beta-Alanine", "150mg Caffeine", "Nitric Oxide Pump", "Zero Sugar"],
    description: "America's legendary pre-workout. CarnoSyn Beta-Alanine buffers lactic acid buildup while anhydrous caffeine and TeaCrine deliver razor-sharp mental focus.",
    badge: "Top Energy",
    badgeColor: "#ef4444",
  },
  {
    id: "7",
    shopType: "common",
    category: "preworkout",
    name: "Doctor's Choice Shred Pro Intense Pre-Workout with Alpha GPC & L-Citrulline",
    brand: "Doctor's Choice",
    asin: "B0892B7P5N",
    price: "₹1,699",
    originalPrice: "₹2,499",
    discount: "32% OFF",
    image: "/products/7.jpg",
    tags: ["6000mg L-Citrulline", "Alpha GPC", "Skin Splitting Pump", "Hardcore Focus"],
    description: "High-stim pre-workout engineered for seasoned lifters. Massive nitric oxide vasodilation combined with Alpha GPC for mind-muscle connection.",
    badge: "Hardcore Pump",
    badgeColor: "#dc2626",
  },
  {
    id: "8",
    shopType: "common",
    category: "vitamins",
    name: "Doctor's Best High Absorption Magnesium Glycinate 100mg Lysinate (120 Tablets)",
    brand: "Doctor's Best",
    asin: "B000BD0RT0",
    price: "₹1,899",
    originalPrice: "₹2,499",
    discount: "24% OFF",
    image: "/products/8.jpg",
    tags: ["TRAACS Chelated", "Zero Laxative Effect", "Deep REM Sleep", "Muscle Spasm Relief"],
    description: "100% chelated with amino acids glycine and lysine. Maximum bioavailability without digestive distress. Relaxes hypertonic muscle fibers and supports deep sleep.",
    badge: "Recovery King",
    badgeColor: "#10b981",
  },
  {
    id: "9",
    shopType: "common",
    category: "vitamins",
    name: "NOW Foods Ultra Omega-3 Deep Sea Fish Oil (500mg EPA / 250mg DHA, 90 Softgels)",
    brand: "NOW Foods",
    asin: "B003O1U16W",
    price: "₹1,799",
    originalPrice: "₹2,399",
    discount: "25% OFF",
    image: "/products/9.jpg",
    tags: ["Molecularly Distilled", "Enteric Coated", "Zero Fishy Burps", "Joint Lubrication"],
    description: "Pharmaceutical grade molecularly distilled cold-water fish oil. High potency EPA/DHA preserves articular cartilage and reduces systemic workout inflammation.",
    badge: "Joint Savior",
    badgeColor: "#3b82f6",
  },
  {
    id: "10",
    shopType: "common",
    category: "vitamins",
    name: "Carbamide Forte Vitamin D3 60000 IU with Vitamin K2 MK7 (120 Chewable Tablets)",
    brand: "Carbamide Forte",
    asin: "B08R7NDW5T",
    price: "₹599",
    originalPrice: "₹899",
    discount: "33% OFF",
    image: "/products/10.jpg",
    tags: ["Cholecalciferol D3", "Menaquinone K2 MK7", "Bone Density", "Immunity Booster"],
    description: "Synergistic D3 and K2 MK7 matrix. Directs elemental calcium into bones and teeth rather than arterial walls, optimizing immune defense and test levels.",
    badge: "Essential D3",
    badgeColor: "#f59e0b",
  },
  {
    id: "11",
    shopType: "common",
    category: "vitamins",
    name: "HealthKart HK Vitals Multivitamin with Zinc, Vitamin C, D3 & Ginseng (60 Tablets)",
    brand: "HealthKart",
    asin: "B08R7NDW5T",
    price: "₹499",
    originalPrice: "₹749",
    discount: "33% OFF",
    image: "/products/11.jpg",
    tags: ["100% RDA Minerals", "Korean Ginseng", "Immunity", "Energy"],
    description: "Complete daily multivitamin with Ginseng extract and 9 essential amino acids to fight workout fatigue and bolster immune health.",
    badge: "Daily Vital",
    badgeColor: "#3b82f6",
  },
  {
    id: "12",
    shopType: "common",
    category: "vitamins",
    name: "Pintola All-Natural Organic Peanut Butter Crunchy 1kg (100% Roasted Peanuts)",
    brand: "Pintola",
    asin: "B07H83LBNP",
    price: "₹449",
    originalPrice: "₹599",
    discount: "25% OFF",
    image: "/products/12.jpg",
    tags: ["30g Protein / 100g", "Zero Added Sugar", "Zero Hydrogenated Oil", "Non-GMO"],
    description: "100% pure roasted peanuts. Zero palm oil, zero sugar, zero emulsifiers. Healthy caloric density for lean bulking and muscle repair.",
    badge: "Top Snack",
    badgeColor: "#f59e0b",
  },
  {
    id: "13",
    shopType: "common",
    category: "gear",
    name: "Harbinger 4-Inch Padded Leather Weightlifting Belt (Heavy Duty Lumbar Support)",
    brand: "Harbinger",
    asin: "B00074H6MI",
    price: "₹2,799",
    originalPrice: "₹3,699",
    discount: "24% OFF",
    image: "/products/13.jpg",
    tags: ["Genuine Split Leather", "Contoured Fit", "Steel Roller Buckle", "Heavy Squats"],
    description: "Full-grain leather with interior foam padding. Stabilizes intra-abdominal pressure during heavy deadlifts, squats, and overhead presses.",
    badge: "Powerlifter Pick",
    badgeColor: "#f59e0b",
  },
  {
    id: "14",
    shopType: "common",
    category: "gear",
    name: "Versa Gripps Pro Weightlifting Straps & Hooks (Official Patented Grip Assist)",
    brand: "Versa Gripps",
    asin: "B007R6X49M",
    price: "₹4,999",
    originalPrice: "₹6,499",
    discount: "23% OFF",
    image: "/products/14.jpg",
    tags: ["Eliminates Grip Fatigue", "Pull Day King", "Quick Release", "Made in USA"],
    description: "Replaces lifting straps and hooks entirely. Locks onto barbells and dumbbells instantaneously, isolating the lats and upper back.",
    badge: "Pro Choice",
    badgeColor: "#8b5cf6",
  },
  {
    id: "15",
    shopType: "common",
    category: "gear",
    name: "Boldfit Heavy Duty Resistance Loop Bands for Workout & Warmup (Set of 5)",
    brand: "Boldfit",
    asin: "B0892B19F6",
    price: "₹499",
    originalPrice: "₹999",
    discount: "50% OFF",
    image: "/products/15.jpg",
    tags: ["100% Natural Latex", "5 Resistance Tiers", "Portability Pouch"],
    description: "Essential for rotator cuff activation, glute bridges, pull-up assistance, and dynamic mobility before heavy compound sessions.",
    badge: "Warm-Up Essential",
    badgeColor: "#10b981",
  },
  {
    id: "16",
    shopType: "common",
    category: "gear",
    name: "Strauss High Density Deep Tissue Foam Roller with Grid Matrix (33cm)",
    brand: "Strauss",
    asin: "B01NAO9IJE",
    price: "₹699",
    originalPrice: "₹1,299",
    discount: "46% OFF",
    image: "/products/16.jpg",
    tags: ["Myofascial Release", "Trigger Point Relief", "EVA Foam", "Durable Core"],
    description: "3D multi-density zones mimic sports therapist fingertips. Breaks down tight muscular adhesions and accelerates lactic acid clearance.",
    badge: "Recovery Essential",
    badgeColor: "#06b6d4",
  },
  {
    id: "17",
    shopType: "common",
    category: "gear",
    name: "HealthSense Ultra-Accurate Bluetooth Smart Body Fat Scale (13 Fitness Metrics)",
    brand: "HealthSense",
    asin: "B07P7H5J4N",
    price: "₹1,799",
    originalPrice: "₹2,999",
    discount: "40% OFF",
    image: "/products/17.jpg",
    tags: ["BIA Technology", "Body Fat %", "Muscle Mass", "Bluetooth Sync"],
    description: "Bioelectrical Impedance Analysis measures visceral fat, skeletal muscle mass, BMR, and hydration percentage. Syncs seamlessly with fitness apps.",
    badge: "High Tech",
    badgeColor: "#3b82f6",
  },
  {
    id: "18",
    shopType: "common",
    category: "gear",
    name: "BlenderBottle Pro Series 820ml Shaker Bottle with Wire Whisk Ball",
    brand: "BlenderBottle",
    asin: "B01LZE4K6U",
    price: "₹899",
    originalPrice: "₹1,299",
    discount: "31% OFF",
    image: "/products/18.jpg",
    tags: ["Eastman Tritan Plastic", "Odor Resistant", "Leak Proof Lid", "BPA Free"],
    description: "Durable Eastman Tritan plastic resists protein odour retention. 316 surgical-grade stainless steel BlenderBall mixes thickest mass gainers silky smooth.",
    badge: "#1 Shaker",
    badgeColor: "#f59e0b",
  },
  {
    id: "19",
    shopType: "common",
    category: "protein",
    name: "Avvatar 100% Whey Protein (Fresh Milk Whey from India, 1kg Malai Kulfi)",
    brand: "Avvatar",
    asin: "B07T7H15R6",
    price: "₹2,499",
    originalPrice: "₹3,199",
    discount: "22% OFF",
    image: "/products/19.jpg",
    tags: ["Fresh Grass-Fed Whey", "28g Protein/Scoop", "Made in India", "Naturally Occurring BCAAs"],
    description: "First 100% genuine fresh milk whey processed within 24 hours of milking at India's automated facility. High bioavailability and zero spiking.",
    badge: "Made in India King",
    badgeColor: "#10b981",
  },
  {
    id: "20",
    shopType: "common",
    category: "protein",
    name: "Isopure Low Carb 100% Whey Protein Isolate (Dutch Chocolate 1kg / 2.2 lbs)",
    brand: "Isopure",
    asin: "B002U7Z6VU",
    price: "₹4,299",
    originalPrice: "₹5,499",
    discount: "22% OFF",
    image: "/products/20.jpg",
    tags: ["100% Whey Isolate", "Zero Added Sugar", "25g Protein", "Microfiltered"],
    description: "Ultra-pure cross-flow micro-filtered whey protein isolate. Exceptionally low carbohydrate and fat profile, perfect for aggressive contest cutting.",
    badge: "Ultra Pure Cut",
    badgeColor: "#8b5cf6",
  },
  {
    id: "21",
    shopType: "common",
    category: "creatine",
    name: "Wellcore Pure Micronized Creatine Monohydrate (Unflavoured 250g, 83 Servings)",
    brand: "Wellcore",
    asin: "B0BW48C7G3",
    price: "₹999",
    originalPrice: "₹1,499",
    discount: "33% OFF",
    image: "/products/21.jpg",
    tags: ["100% Micronized", "Zero Fillers", "ATP Re-synthesis", "Explosive Power"],
    description: "Micro-milled particles ensure instantaneous suspension in water with zero gritty texture. Re-synthesizes intracellular phosphocreatine rapidly.",
    badge: "Trending Power",
    badgeColor: "#f59e0b",
  },
  {
    id: "22",
    shopType: "common",
    category: "preworkout",
    name: "Scivation Xtend Original BCAA (Blue Raspberry 30 Servings)",
    brand: "Scivation",
    asin: "B005CH0DT4",
    price: "₹2,199",
    originalPrice: "₹2,999",
    discount: "27% OFF",
    image: "/products/22.jpg",
    tags: ["7g BCAAs 2:1:1", "Hydration Electrolytes", "Zero Calorie", "Intra-Workout"],
    description: "The world champion intra-workout. Supplies 7g of 2:1:1 BCAAs with key electrolytes to sustain muscle protein synthesis mid-session.",
    badge: "Top Intra-Workout",
    badgeColor: "#06b6d4",
  },
  {
    id: "23",
    shopType: "common",
    category: "vitamins",
    name: "Fast&Up Charge 1000mg Natural Amla Vitamin C + Zinc Effervescent (60 Tablets)",
    brand: "Fast&Up",
    asin: "B0716QRP6M",
    price: "₹699",
    originalPrice: "₹1,050",
    discount: "33% OFF",
    image: "/products/23.jpg",
    tags: ["Natural Amla Extract", "Effervescent Fizz", "Immune Defense", "Informed Choice Certified"],
    description: "Bioavailable Indian gooseberry (Amla) extract with elemental Zinc. Fizz action speeds gastric emptying and antioxidant absorption.",
    badge: "Immunity Shield",
    badgeColor: "#f59e0b",
  },
  {
    id: "24",
    shopType: "common",
    category: "vitamins",
    name: "TrueBasics Omega 3 Fish Oil Triple Strength (1250mg, 560mg EPA / 400mg DHA, 60 Caps)",
    brand: "TrueBasics",
    asin: "B07H8312Q9",
    price: "₹899",
    originalPrice: "₹1,399",
    discount: "36% OFF",
    image: "/products/24.jpg",
    tags: ["Triple Strength", "Molecularly Distilled", "Zero Fishy Burps", "Joint Health"],
    description: "Cold-water sardine and anchovy oil purified via vacuum molecular distillation to eliminate heavy metals. Crucial for joint lubrication and systemic inflammation.",
    badge: "Heart & Joints",
    badgeColor: "#3b82f6",
  },
  {
    id: "25",
    shopType: "common",
    category: "gear",
    name: "Boldfit Heavy-Duty Elastic Wrist Wraps for Heavy Bench Press & OHP (Pair)",
    brand: "Boldfit",
    asin: "B08HVS221Q",
    price: "₹399",
    originalPrice: "₹699",
    discount: "43% OFF",
    image: "/products/25.jpg",
    tags: ["Reinforced Thumb Loop", "Heavy Elastic Weave", "Zero Wrist Strain", "Heavy Bench"],
    description: "Prevents hyperextension of carpal bones under heavy barbell loads. High-grade thumb loop locks placement firmly throughout max effort presses.",
    badge: "Lifting Essential",
    badgeColor: "#ef4444",
  },
  {
    id: "26",
    shopType: "common",
    category: "gear",
    name: "Dr Trust USA Smart Digital Kitchen Nutrition & Food Scale (1g to 5kg)",
    brand: "Dr Trust",
    asin: "B01M335508",
    price: "₹899",
    originalPrice: "₹1,500",
    discount: "40% OFF",
    image: "/products/26.jpg",
    tags: ["Precision 1g Sensors", "Tare Function", "Tempered Glass", "Macro Tracking"],
    description: "Accurate portion weighing is 80% of muscle building and fat loss. High-precision strain gauge sensors track rice, oats, chicken, and powders in grams.",
    badge: "Diet Master",
    badgeColor: "#10b981",
  },
  {
    id: "27",
    shopType: "common",
    category: "gear",
    name: "Joyfit 11-Piece Heavy Resistance Tube Set with Door Anchor & Ankle Straps",
    brand: "Joyfit",
    asin: "B08K39Q9X1",
    price: "₹1,299",
    originalPrice: "₹2,499",
    discount: "48% OFF",
    image: "/products/27.jpg",
    tags: ["Stackable Up to 150 lbs", "Door Anchor Included", "Travel Gym", "Ankle Straps"],
    description: "Complete home workout system. 5 stackable resistance tubes with steel carabiners deliver linear resistance curves for bicep curls, chest flies, and lateral raises.",
    badge: "Portable Gym",
    badgeColor: "#8b5cf6",
  },
  {
    id: "28",
    shopType: "common",
    category: "gear",
    name: "Nivia Heavy Duty High-Speed Bearing Jump / Skipping Rope",
    brand: "Nivia",
    asin: "B0111U8Q2E",
    price: "₹349",
    originalPrice: "₹599",
    discount: "42% OFF",
    image: "/products/28.jpg",
    tags: ["360 Degree Ball Bearings", "Tangle-Free Cable", "HIIT Conditioning", "Cardio Burn"],
    description: "Smooth 360-degree rotation ball bearings enable effortless double-unders and high-velocity cardio sessions without cable twisting.",
    badge: "Cardio Beast",
    badgeColor: "#f59e0b",
  },
  {
    id: "29",
    shopType: "common",
    category: "vitamins",
    name: "Yogabars 20g Whey Protein Bar (Variety Pack of 6 Bars, Almond Fudge & Chocolate)",
    brand: "Yogabars",
    asin: "B07S7XFGGN",
    price: "₹649",
    originalPrice: "₹780",
    discount: "17% OFF",
    image: "/products/29.jpg",
    tags: ["20g Whey Protein", "10g Dietary Fiber", "Zero Soy Protein", "No Preservatives"],
    description: "Delicious post-workout grab-and-go snack. Powered by whey isolate and concentrate blend with zero artificial sweeteners or vegetable fats.",
    badge: "High Protein Snack",
    badgeColor: "#f97316",
  },
  {
    id: "30",
    shopType: "common",
    category: "gear",
    name: "Vector X Leather Padded Weight Lifting Gym Gloves with Built-In Wrist Wrap",
    brand: "Vector X",
    asin: "B00I4UI1W0",
    price: "₹499",
    originalPrice: "₹850",
    discount: "41% OFF",
    image: "/products/30.jpg",
    tags: ["Genuine Leather Palm", "Anti-Callus Foam", "Breathable Mesh", "Wrist Support"],
    description: "Combines palm callus protection with an extended wrist stabilizer wrap. Micro-perforated back panel keeps palms cool during grueling workouts.",
    badge: "Callus Shield",
    badgeColor: "#64748b",
  },
];

// ── DEDICATED MEN'S HEALTH, VITALITY & PERFORMANCE PRODUCTS (24 Items) ──
export const MALE_PRODUCTS = [
  {
    id: "101",
    shopType: "male",
    category: "testosterone",
    name: "Kapiva Himalayan Pure Shilajit Gold Resin with 24K Gold Dust (20g)",
    brand: "Kapiva",
    asin: "B09G3F3Q8X",
    price: "₹1,499",
    originalPrice: "₹1,999",
    discount: "25% OFF",
    image: "/products/101.jpg",
    tags: ["Surya Tapi Processed", "Swarna Bhasma 24K", "75%+ Fulvic Acid", "Stamina & T-Levels"],
    description: "Sourced from 18,000 ft in the Himalayas. Infused with Swarna Bhasma (24K Gold), Ashwagandha, and Gokshura for maximum stamina, endurance, and natural testosterone.",
    badge: "#1 Vitality",
    badgeColor: "#f59e0b",
  },
  {
    id: "102",
    shopType: "male",
    category: "testosterone",
    name: "Himalaya Organic KSM-66 Ashwagandha Root Extract (60 Tablets, Stress & Cortisol)",
    brand: "Himalaya",
    asin: "B0106W6ZQE",
    price: "₹499",
    originalPrice: "₹650",
    discount: "23% OFF",
    image: "/products/102.jpg",
    tags: ["KSM-66 Certified", "Full Spectrum", "Lowers Cortisol", "Deep Sleep"],
    description: "Gold standard full-spectrum root extract. Lowers serum cortisol by up to 27%, facilitating natural nocturnal free testosterone synthesis and recovery.",
    badge: "Clinical Ashwagandha",
    badgeColor: "#3b82f6",
  },
  {
    id: "103",
    shopType: "male",
    category: "testosterone",
    name: "Momentous Huberman Lab Tongkat Ali 400mg Pure Root Extract (60 Capsules)",
    brand: "Momentous",
    asin: "B0B6Q7Z8F1",
    price: "₹2,899",
    originalPrice: "₹3,599",
    discount: "20% OFF",
    image: "/products/103.jpg",
    tags: ["Eurycoma Longifolia", "Unbinds Free Testosterone", "Huberman Protocol", "Pure Extract"],
    description: "Endorsed by neuroscientist Dr. Andrew Huberman. Unbinds SHBG, liberating bioavailable free testosterone for aggressive gym drive and recovery.",
    badge: "Neuro Protocol",
    badgeColor: "#8b5cf6",
  },
  {
    id: "104",
    shopType: "male",
    category: "testosterone",
    name: "Swanson Peruvian Black Maca Root High Potency (750mg, 60 Capsules)",
    brand: "Swanson",
    asin: "B00822YA96",
    price: "₹1,299",
    originalPrice: "₹1,699",
    discount: "24% OFF",
    image: "/products/104.jpg",
    tags: ["Rare Black Maca", "Andean Superfood", "Male Libido", "Cellular Energy"],
    description: "The rarest of maca varieties. Known for centuries by Andean warriors to support male reproductive vigor, stamina, and endocrine balance.",
    badge: "Superfood Vigor",
    badgeColor: "#10b981",
  },
  {
    id: "105",
    shopType: "male",
    category: "recovery",
    name: "Optimum Nutrition ZMA Zinc, Magnesium Aspartate & Vitamin B6 (90 Veg Capsules)",
    brand: "Optimum Nutrition",
    asin: "B000GIQS3E",
    price: "₹1,899",
    originalPrice: "₹2,499",
    discount: "24% OFF",
    image: "/products/105.jpg",
    tags: ["Patented SNAC ZMA", "Nighttime Recovery", "Anabolic Sleep", "Immune Defense"],
    description: "Synergistic mineral blend formulated to replace zinc and magnesium lost during intense physical exertion. Encourages deeper stages of sleep.",
    badge: "Recovery Standard",
    badgeColor: "#06b6d4",
  },
  {
    id: "106",
    shopType: "male",
    category: "testosterone",
    name: "NOW Foods Boron 3mg Pure Elemental Mineral for Free Testosterone (250 Capsules)",
    brand: "NOW Foods",
    asin: "B00013YZ82",
    price: "₹1,199",
    originalPrice: "₹1,599",
    discount: "25% OFF",
    image: "/products/106.jpg",
    tags: ["Bororganic Glycine", "Decreases SHBG", "Optimizes Free T", "Joint Support"],
    description: "Trace mineral shown in clinical studies to significantly decrease Sex Hormone Binding Globulin (SHBG) within 7 days, liberating bioavailable free testosterone.",
    badge: "Free-T Booster",
    badgeColor: "#3b82f6",
  },
  {
    id: "107",
    shopType: "male",
    category: "recovery",
    name: "Doctor's Best CoQ10 200mg with BioPerine Black Pepper Extract (60 Softgels)",
    brand: "Doctor's Best",
    asin: "B0019GW3G8",
    price: "₹2,199",
    originalPrice: "₹2,899",
    discount: "24% OFF",
    image: "/products/107.jpg",
    tags: ["Fermented CoQ10", "BioPerine Absorption", "Mitochondrial Energy", "Heart Muscle"],
    description: "Vital cofactor in mitochondrial adenosine triphosphate (ATP) synthesis. BioPerine enhances absorption, supporting myocardial tissue and endothelial function.",
    badge: "Cellular Energy",
    badgeColor: "#f59e0b",
  },
  {
    id: "108",
    shopType: "male",
    category: "muscle",
    name: "PrimaForce Pure L-Citrulline Malate 200g Powder (Nitric Oxide & Massive Vasodilation)",
    brand: "PrimaForce",
    asin: "B00E774H6W",
    price: "₹1,799",
    originalPrice: "₹2,499",
    discount: "28% OFF",
    image: "/products/108.jpg",
    tags: ["2:1 Citrulline Malate", "Endothelial NO", "Arterial Flexibility", "Huge Muscle Pump"],
    description: "Bypasses liver arginase directly into bloodstream. Increases plasma arginine concentrations more effectively than L-Arginine itself for superior pumps.",
    badge: "Pump Weapon",
    badgeColor: "#ef4444",
  },
  {
    id: "109",
    shopType: "male",
    category: "sexual",
    name: "Durex Naturals Pure Intimate Water-Based Lubricant with Natural Prebiotics (100ml)",
    brand: "Durex",
    asin: "B07NWZ2H9Z",
    price: "₹449",
    originalPrice: "₹599",
    discount: "25% OFF",
    image: "/products/109.jpg",
    tags: ["100% Natural Ingredients", "pH Friendly", "Prebiotic Enriched", "Gentle & Non-Greasy"],
    description: "Water-based formula made with 100% natural ingredients and prebiotics to support skin flora. Non-staining, ultra-smooth for sexual wellness.",
    badge: "Gentle Care",
    badgeColor: "#ec4899",
  },
  {
    id: "110",
    shopType: "male",
    category: "gear",
    name: "Harbinger Heavy Duty Dip & Pull-Up Belt with 34-Inch Steel Chain",
    brand: "Harbinger",
    asin: "B001PB4UI2",
    price: "₹2,999",
    originalPrice: "₹3,999",
    discount: "25% OFF",
    image: "/products/110.jpg",
    tags: ["Contoured Polypropylene", "Heavy Duty Steel Chain", "Overload Weighted Dips", "150kg Tested"],
    description: "Designed for weighted dips, pull-ups, and belt squats. Contoured back padding relieves lower back shearing forces while securely loading 50kg+ plates.",
    badge: "Calisthenics Beast",
    badgeColor: "#3b82f6",
  },
  {
    id: "111",
    shopType: "male",
    category: "gear",
    name: "SBD Powerlifting 10mm Competition Lever Belt (English Bridle Leather)",
    brand: "SBD Apparel",
    asin: "B08M3XKGKZ",
    price: "₹18,999",
    originalPrice: "₹22,999",
    discount: "18% OFF",
    image: "/products/111.jpg",
    tags: ["Patented Gliding Lever", "IPF Approved", "English Bridle Leather", "World Record Support"],
    description: "The crown jewel of powerlifting belts. Patented gliding lever allows instant adjustments without a screwdriver. Extreme intra-abdominal bracing.",
    badge: "World Champion",
    badgeColor: "#f59e0b",
  },
  {
    id: "112",
    shopType: "male",
    category: "gear",
    name: "RDX Heavy Duty Weightlifting Wrist Wraps with Thumb Loop (Pair)",
    brand: "RDX",
    asin: "B00KAE3B7C",
    price: "₹899",
    originalPrice: "₹1,299",
    discount: "31% OFF",
    image: "/products/112.jpg",
    tags: ["Heavy Elastic Weave", "Hook & Loop Closure", "Eliminates Wrist Shearing", "Heavy OHP"],
    description: "High-density elastic woven specifically for heavy overhead presses and bench presses. Stabilizes the wrist joint against hyperextension under max load.",
    badge: "Heavy Duty",
    badgeColor: "#10b981",
  },
  {
    id: "113",
    shopType: "male",
    category: "grooming",
    name: "Man Matters Anti-Hairfall Onion & Biotin Shampoo with Saw Palmetto (200ml)",
    brand: "Man Matters",
    asin: "B08B9N8W7P",
    price: "₹399",
    originalPrice: "₹599",
    discount: "33% OFF",
    image: "/products/113.jpg",
    tags: ["DHT Blocker Formula", "Saw Palmetto Extract", "Zero Sulfates", "Scalp Nourishment"],
    description: "Formulated specifically for men experiencing early temporal hairline recession. Saw Palmetto blocks scalp 5-alpha reductase, preventing follicle miniaturization.",
    badge: "Hair Defense",
    badgeColor: "#06b6d4",
  },
  {
    id: "114",
    shopType: "male",
    category: "gear",
    name: "SBD Heavy-Duty Neoprene 7mm Knee Sleeves (Competition Level Support)",
    brand: "SBD",
    asin: "B01N0PZ6Z6",
    price: "₹6,499",
    originalPrice: "₹8,499",
    discount: "24% OFF",
    image: "/products/114.jpg",
    tags: ["7mm High Grade Neoprene", "IPF Approved", "Heavy Squatting", "Patella Warmth"],
    description: "The gold standard knee sleeves for powerlifters and heavy squatters. Delivers immense rebound warmth, patella tracking, and joint stabilization.",
    badge: "IPF Legal",
    badgeColor: "#3b82f6",
  },
  {
    id: "115",
    shopType: "male",
    category: "testosterone",
    name: "TrueBasics KSM-66 Ashwagandha with Korean Ginseng & Vitamin D3 (60 Veg Capsules)",
    brand: "TrueBasics",
    asin: "B084DV1635",
    price: "₹999",
    originalPrice: "₹1,499",
    discount: "33% OFF",
    image: "/products/115.jpg",
    tags: ["KSM-66 Full Spectrum", "Korean Ginseng", "Cortisol Blocker", "Stress Relief"],
    description: "Standardized 5% withanolides reduce evening salivary cortisol, facilitating deep REM sleep and natural morning testosterone surges.",
    badge: "Vitality Formula",
    badgeColor: "#3b82f6",
  },
  {
    id: "116",
    shopType: "male",
    category: "testosterone",
    name: "Rasayanam Pure Himalayan Shilajit (30g Semi-Liquid Resin with Wooden Spoon)",
    brand: "Rasayanam",
    asin: "B093C4C6N2",
    price: "₹1,399",
    originalPrice: "₹1,999",
    discount: "30% OFF",
    image: "/products/116.jpg",
    tags: ["75%+ Fulvic Acid", "Sourced from 18,000 ft", "Lab Tested NABL", "Endurance"],
    description: "Purified via traditional Surya Tapi ayurvedic methodology. Rich in fulvic acid and 84+ ionic trace minerals that optimize cellular ATP output.",
    badge: "Gold Standard Resin",
    badgeColor: "#f59e0b",
  },
  {
    id: "117",
    shopType: "male",
    category: "sexual",
    name: "Carbamide Forte L-Arginine 1000mg Nitric Oxide Precursor (120 Tablets)",
    brand: "Carbamide Forte",
    asin: "B07W8414T7",
    price: "₹599",
    originalPrice: "₹900",
    discount: "33% OFF",
    image: "/products/117.jpg",
    tags: ["1000mg Free Form", "Nitric Oxide Booster", "Vasodilation", "Vascularity & Drive"],
    description: "Direct precursor to endothelial nitric oxide. Dilates arterial walls, enhancing peripheral blood circulation, athletic pump, and male performance.",
    badge: "Nitric Oxide Pump",
    badgeColor: "#ef4444",
  },
  {
    id: "118",
    shopType: "male",
    category: "testosterone",
    name: "Himalaya Gokshura (Tribulus Terrestris 60 Tablets for Male Stamina & Kidney Support)",
    brand: "Himalaya",
    asin: "B00822YA96",
    price: "₹249",
    originalPrice: "₹350",
    discount: "29% OFF",
    image: "/products/118.jpg",
    tags: ["Pure Gokshura", "Saponin Rich", "Urinary Tract Support", "Ayurvedic Vigor"],
    description: "Ancient Rasayana herb known for supporting libido, uro-genital tract health, and vigorous athletic recovery without artificial stimulants.",
    badge: "Ayurvedic Classic",
    badgeColor: "#10b981",
  },
  {
    id: "119",
    shopType: "male",
    category: "grooming",
    name: "Man Matters 5% Minoxidil Topical Solution with Finasteride for Hair Regrowth (60ml)",
    brand: "Man Matters",
    asin: "B08NTR5W4X",
    price: "₹799",
    originalPrice: "₹1,199",
    discount: "33% OFF",
    image: "/products/119.jpg",
    tags: ["5% Minoxidil", "Alcohol Free Base", "Follicle Reactivation", "DHT Blocker"],
    description: "Clinically proven formula that reactivates dormant hair follicles and widens micro-vessels in the scalp, reversing male pattern thinning.",
    badge: "Hair Rescue",
    badgeColor: "#06b6d4",
  },
  {
    id: "120",
    shopType: "male",
    category: "grooming",
    name: "Beardo Dark Fantasy Beard Growth Oil with Sesame & Rose Oil (50ml)",
    brand: "Beardo",
    asin: "B01L1EZC4Q",
    price: "₹399",
    originalPrice: "₹750",
    discount: "47% OFF",
    image: "/products/120.jpg",
    tags: ["Natural Sesame Oil", "Non-Greasy", "Beard Softener", "Patchy Beard Relief"],
    description: "Enriched with natural botanical extracts to moisturize underlying skin, tame unruly bristles, and stimulate patchy facial hair growth.",
    badge: "Beard Master",
    badgeColor: "#f59e0b",
  },
  {
    id: "121",
    shopType: "male",
    category: "testosterone",
    name: "MuscleBlaze TestoCore Testosterone Booster with Fenugreek & Safed Musli (60 Tabs)",
    brand: "MuscleBlaze",
    asin: "B08GCSX3G8",
    price: "₹1,199",
    originalPrice: "₹1,799",
    discount: "33% OFF",
    image: "/products/121.jpg",
    tags: ["Testofen Fenugreek", "Safed Musli", "Kaunch Beej", "D-Aspartic Acid"],
    description: "Synergistic botanical and mineral matrix engineered to support free testosterone indices and combat workout lethargy.",
    badge: "Hardcore Blend",
    badgeColor: "#ef4444",
  },
  {
    id: "122",
    shopType: "male",
    category: "testosterone",
    name: "Nutrabay Pure Maca Root Extract 500mg High Potency (60 Vegan Capsules)",
    brand: "Nutrabay",
    asin: "B08P1Q1T2K",
    price: "₹549",
    originalPrice: "₹899",
    discount: "39% OFF",
    image: "/products/122.jpg",
    tags: ["Andean Maca Root", "Adaptogenic Stamina", "Zero Additives", "Daily Vitality"],
    description: "Peruvian superfood adaptogen that supports endocrine homeostasis, physical energy levels, and mood resilience.",
    badge: "Adaptogen Pick",
    badgeColor: "#10b981",
  },
  {
    id: "123",
    shopType: "male",
    category: "gear",
    name: "Boldfit Compression Gym Shorts & Athletic Supporter with Moisture Wicking",
    brand: "Boldfit",
    asin: "B08F2H57KP",
    price: "₹499",
    originalPrice: "₹999",
    discount: "50% OFF",
    image: "/products/123.jpg",
    tags: ["4-Way Stretch Lycra", "Groin Protection Pocket", "Anti-Chafing", "Ergonomic Fit"],
    description: "Provides firm compression to quads and groin area during heavy squats and high-impact sprints, drastically reducing chafing and groin strains.",
    badge: "Training Armor",
    badgeColor: "#3b82f6",
  },
  {
    id: "124",
    shopType: "male",
    category: "grooming",
    name: "Ustraa Hair Growth Vitalizer with Redensyl, Saw Palmetto & Biotin (100ml)",
    brand: "Ustraa",
    asin: "B073PWG3C5",
    price: "₹649",
    originalPrice: "₹999",
    discount: "35% OFF",
    image: "/products/124.jpg",
    tags: ["Redensyl Active", "Saw Palmetto DHT Shield", "Biotin + Wheat Germ", "Non-Sticky"],
    description: "Formulated specifically for men struggling with hairline recession. Saw Palmetto blocks 5-alpha reductase while Redensyl re-energizes stem cells.",
    badge: "Scalp Defense",
    badgeColor: "#64748b",
  },
];

// ── DEDICATED WOMEN'S HEALTH, PCOS & HORMONAL WELLNESS PRODUCTS (24 Items) ──
export const FEMALE_PRODUCTS = [
  {
    id: "201",
    shopType: "female",
    category: "pcos",
    name: "Wholesome Story Myo-Inositol & D-Chiro Inositol (40:1 Ratio, 120 Veg Capsules)",
    brand: "Wholesome Story",
    asin: "B07TXLSG51",
    price: "₹2,699",
    originalPrice: "₹3,599",
    discount: "25% OFF",
    image: "/products/201.jpg",
    tags: ["40:1 Physiological Ratio", "Insulin Sensitizer", "Ovulatory Support", "PCOS Certified"],
    description: "The golden medical ratio 40:1 of Myo-Inositol to D-Chiro Inositol. Clinically shown to improve ovarian function, restore regular menstrual cycles, and reduce androgenic acne.",
    badge: "#1 PCOS Choice",
    badgeColor: "#ec4899",
  },
  {
    id: "202",
    shopType: "female",
    category: "pcos",
    name: "Vahdam Pure Kashmiri Organic Spearmint Tea for PCOS & Hormones (50 Tea Bags)",
    brand: "Vahdam India",
    asin: "B0786H7W2K",
    price: "₹499",
    originalPrice: "₹699",
    discount: "29% OFF",
    image: "/products/202.jpg",
    tags: ["Anti-Androgenic", "Hirsutism Relief", "Kashmiri Grown", "Zero Caffeine"],
    description: "Clinically demonstrated anti-androgenic effects. Drinking two cups daily significantly reduces free testosterone levels responsible for facial hair growth (hirsutism) and cystic acne.",
    badge: "Hormone Detox",
    badgeColor: "#10b981",
  },
  {
    id: "203",
    shopType: "female",
    category: "pcos",
    name: "Thorne Research Berberine 500mg (60 Capsules for Metabolic & Glucose Support)",
    brand: "Thorne",
    asin: "B003HX6WEA",
    price: "₹3,199",
    originalPrice: "₹4,199",
    discount: "24% OFF",
    image: "/products/203.jpg",
    tags: ["AMPK Activator", "Insulin Sensitivity", "PCOS Weight Balance", "Microbiome Support"],
    description: "Natural plant alkaloid that activates AMPK enzymes. Proven in clinical studies to be as potent as standard metformin in resolving PCOS insulin resistance without GI distress.",
    badge: "Doctor Vetted",
    badgeColor: "#3b82f6",
  },
  {
    id: "204",
    shopType: "female",
    category: "pcos",
    name: "Organic India Shatavari Ayurvedic Root Extract for Female Hormone Balance (60 Veg Caps)",
    brand: "Organic India",
    asin: "B001G7R19G",
    price: "₹349",
    originalPrice: "₹499",
    discount: "30% OFF",
    image: "/products/204.jpg",
    tags: ["Asparagus Racemosus", "Estrogen Adaptogen", "Follicular Health", "Ayurvedic Gold"],
    description: "The Queen of Herbs for female vitality. Phytoestrogens gently balance natural estrogen fluctuations, soothe PMS mood swings, and nourish reproductive mucosal tissue.",
    badge: "Ayurvedic Queen",
    badgeColor: "#8b5cf6",
  },
  {
    id: "205",
    shopType: "female",
    category: "pcos",
    name: "Nature's Way Vitex Chasteberry Fruit 400mg (100 Vegan Capsules)",
    brand: "Nature's Way",
    asin: "B00028OUBG",
    price: "₹1,499",
    originalPrice: "₹1,999",
    discount: "25% OFF",
    image: "/products/205.jpg",
    tags: ["Prolactin Regulator", "Luteal Phase Support", "Progesterone Boost", "PMS Relief"],
    description: "Stimulates luteinizing hormone (LH) and moderates prolactin secretion from the pituitary gland. Restores natural progesterone levels for pain-free menstruation.",
    badge: "Cycle Regulator",
    badgeColor: "#f59e0b",
  },
  {
    id: "206",
    shopType: "female",
    category: "period",
    name: "Doctor's Best Magnesium Glycinate 100mg Lysinate (120 Tablets, Cramp Relief)",
    brand: "Doctor's Best",
    asin: "B000BD0RT0",
    price: "₹1,899",
    originalPrice: "₹2,499",
    discount: "24% OFF",
    image: "/products/206.jpg",
    tags: ["Relieves Uterine Cramps", "Deep Relaxation", "Zero Laxative Effect", "Chelated"],
    description: "Calms involuntary uterine smooth muscle contractions that trigger dysmenorrhea and severe menstrual cramps. Promotes parasympathetic relaxation and sound sleep.",
    badge: "Anti-Cramp Gold",
    badgeColor: "#ec4899",
  },
  {
    id: "207",
    shopType: "female",
    category: "period",
    name: "Sirona Reusable Medical-Grade Silicone Menstrual Cup with Breathable Pouch",
    brand: "Sirona",
    asin: "B0797MGHRW",
    price: "₹349",
    originalPrice: "₹499",
    discount: "30% OFF",
    image: "/products/207.jpg",
    tags: ["100% Medical Silicone", "10-Hour Leak Free", "Zero Rashes", "Eco-Friendly 5 Years"],
    description: "Ultra-soft, 100% biocompatible medical silicone. Provides 8-10 hours of leak-free freedom without rashes, dryness, or micro-plastic contact during training and sleep.",
    badge: "Eco Hero",
    badgeColor: "#10b981",
  },
  {
    id: "208",
    shopType: "female",
    category: "period",
    name: "Carmesi Organic Cotton Biodegradable Sanitary Pads (30 Pads with Disposal Bags)",
    brand: "Carmesi",
    asin: "B07J54K5LK",
    price: "₹499",
    originalPrice: "₹699",
    discount: "29% OFF",
    image: "/products/208.jpg",
    tags: ["Pure Cotton Top-sheet", "Zero Chlorine", "Zero Fragrance", "Rash-Free Guarantee"],
    description: "Pure organic cotton top-sheet free from synthetic fragrances, chemical bleaches, and plastics. Eliminates vaginal irritation, contact dermatitis, and period rash.",
    badge: "Rash-Free Cotton",
    badgeColor: "#ec4899",
  },
  {
    id: "209",
    shopType: "female",
    category: "period",
    name: "Nua Cramp Comfort Self-Heating Menstrual Heat Patches (Pack of 3 Heat Wraps)",
    brand: "Nua",
    asin: "B0892D13R8",
    price: "₹299",
    originalPrice: "₹399",
    discount: "25% OFF",
    image: "/products/209.jpg",
    tags: ["8 Hours Continuous Heat", "100% Drug-Free", "Air-Activated", "Discreet & Adhesive"],
    description: "Air-activated therapeutic heat wrap that delivers continuous 8 hours of soothing warmth to the lower abdomen. Relaxes uterine spasming without analgesic medication.",
    badge: "Cramp Soother",
    badgeColor: "#f59e0b",
  },
  {
    id: "210",
    shopType: "female",
    category: "skin",
    name: "Vital Proteins Wild Caught Marine Collagen Peptides (Unflavoured 221g)",
    brand: "Vital Proteins",
    asin: "B07J3H478Y",
    price: "₹3,499",
    originalPrice: "₹4,499",
    discount: "22% OFF",
    image: "/products/210.jpg",
    tags: ["Type 1 & 3 Peptides", "Dermis Elasticity", "Nail & Hair Strength", "Wild Caught"],
    description: "Type 1 & 3 marine peptides derived from wild-caught white fish. Fortifies bone mineral density, joint cartilage, and youthful dermis elasticity.",
    badge: "Collagen Gold",
    badgeColor: "#3b82f6",
  },
  {
    id: "211",
    shopType: "female",
    category: "vitamins",
    name: "Solgar Gentle Chelated Iron 25mg Non-Constipating (90 Vegetable Capsules)",
    brand: "Solgar",
    asin: "B00013Z0PM",
    price: "₹1,499",
    originalPrice: "₹1,999",
    discount: "25% OFF",
    image: "/products/211.jpg",
    tags: ["Iron Bisglycinate", "Zero Constipation", "Zero Nausea", "Replenishes Ferritin"],
    description: "Chelated iron bisglycinate is gentle on delicate gastric lining. Rapidly replenishes ferritin reserves depleted during heavy menstrual bleeding without nausea.",
    badge: "Gentle Iron",
    badgeColor: "#ef4444",
  },
  {
    id: "212",
    shopType: "female",
    category: "intimate",
    name: "Durex Naturals Intimate Lubricant with Aloe Vera & Prebiotics (100ml)",
    brand: "Durex",
    asin: "B07NWZ2H9Z",
    price: "₹449",
    originalPrice: "₹599",
    discount: "25% OFF",
    image: "/products/212.jpg",
    tags: ["pH 4.0 Balanced", "Water-Soluble", "Aloe Vera Enriched", "Gynecologist Safe"],
    description: "Natural water-based lube with soothing organic aloe vera. Formulated to match vaginal acidic pH, providing hydration during hormonal fluctuations.",
    badge: "Intimate Care",
    badgeColor: "#ec4899",
  },
  {
    id: "213",
    shopType: "female",
    category: "skin",
    name: "UrbanBotanics Pure Cold-Pressed Virgin Castor Oil for Eyebrows & Hair (200ml)",
    brand: "UrbanBotanics",
    asin: "B07PBBN2Y3",
    price: "₹299",
    originalPrice: "₹450",
    discount: "34% OFF",
    image: "/products/213.jpg",
    tags: ["100% Pure Ricinoleic Acid", "Eyebrow Density", "Pelvic Heat Packs", "Chemical Free"],
    description: "Hexane-free cold-pressed castor oil rich in ricinoleic acid. Stimulates hair follicle microcirculation and functions as an ideal soothing pack for uterine pain.",
    badge: "Natural Remedy",
    badgeColor: "#10b981",
  },
  {
    id: "214",
    shopType: "female",
    category: "gear",
    name: "Boldfit Fabric Booty Resistance Hip Bands for Glute Activation (Set of 3)",
    brand: "Boldfit",
    asin: "B0892D5Z20",
    price: "₹599",
    originalPrice: "₹1,299",
    discount: "54% OFF",
    image: "/products/214.jpg",
    tags: ["Non-Slip Fabric", "No Pinching", "Glute Hypertrophy", "3 Resistance Levels"],
    description: "Premium cotton-elastic blend with inner non-slip grip strips. Never rolls or snaps during hip thrusts, squats, and Romanian deadlifts.",
    badge: "#1 Glute Band",
    badgeColor: "#ec4899",
  },
  {
    id: "215",
    shopType: "female",
    category: "pcos",
    name: "Oziva Plant-Based HerBalance for PCOS/PCOD with Shatavari & Chasteberry (250g)",
    brand: "Oziva",
    asin: "B07Y7H789Z",
    price: "₹899",
    originalPrice: "₹1,199",
    discount: "25% OFF",
    image: "/products/215.jpg",
    tags: ["8 Clean Herbs", "Inositol Support", "Period Regularity", "Acne & Weight Support"],
    description: "Clinically vetted Ayurvedic herbs combined with whole-food nutrients to balance LH/FSH ratio, regulate ovulation, and soothe androgenic symptoms.",
    badge: "PCOS Hero",
    badgeColor: "#ec4899",
  },
  {
    id: "216",
    shopType: "female",
    category: "skin",
    name: "Wellbeing Nutrition Marine Collagen Peptides Types 1 & 3 (200g Mango Peach)",
    brand: "Wellbeing Nutrition",
    asin: "B08YRP9W9R",
    price: "₹1,999",
    originalPrice: "₹2,699",
    discount: "26% OFF",
    image: "/products/216.jpg",
    tags: ["Deep Sea Korean Collagen", "Hyaluronic Acid", "Skin Firmness", "Nail & Hair Health"],
    description: "Hydrolyzed low-molecular weight peptides for rapid cellular absorption. Rebuilds dermis extracellular matrix for plump skin and reduced fine lines.",
    badge: "Glow Elixir",
    badgeColor: "#f59e0b",
  },
  {
    id: "217",
    shopType: "female",
    category: "intimate",
    name: "Pee Safe Natural Intimate Wash for Women with Tea Tree Oil & Witch Hazel (105ml)",
    brand: "Pee Safe",
    asin: "B075C51997",
    price: "₹249",
    originalPrice: "₹399",
    discount: "38% OFF",
    image: "/products/217.jpg",
    tags: ["pH 3.5 Balanced", "Tea Tree Antimicrobial", "Paraben Free", "Gynecologist Approved"],
    description: "Maintains optimal vaginal acidic pH 3.5, guarding against recurrent candidiasis, odor, and bacterial vaginosis without disrupting normal flora.",
    badge: "Daily Intimate",
    badgeColor: "#06b6d4",
  },
  {
    id: "218",
    shopType: "female",
    category: "pcos",
    name: "Teacurry 100% Organic Spearmint Tea for Facial Hair & Hormonal Balance (30 Bags)",
    brand: "Teacurry",
    asin: "B08L7V894G",
    price: "₹399",
    originalPrice: "₹599",
    discount: "33% OFF",
    image: "/products/218.jpg",
    tags: ["Spearmint Leaves", "Anti-Androgenic", "Hirsutism Support", "Zero Caffeine"],
    description: "Traditional herbal remedy showing proven anti-androgenic effects in multiple randomized trials. Curbs excessive DHT-driven facial hair growth.",
    badge: "Anti-Hirsutism",
    badgeColor: "#10b981",
  },
  {
    id: "219",
    shopType: "female",
    category: "skin",
    name: "Plum 15% Vitamin C Face Serum with Mandarin & Kakadu Plum (30ml)",
    brand: "Plum",
    asin: "B093DFH4P3",
    price: "₹649",
    originalPrice: "₹899",
    discount: "28% OFF",
    image: "/products/219.jpg",
    tags: ["15% Ethyl Ascorbic Acid", "Fades Dark Spots", "Kakadu Plum", "Fragrance Free"],
    description: "Potent stable antioxidant serum that lightens post-inflammatory hyperpigmentation (PIH) and sun damage while boosting natural collagen synthesis.",
    badge: "Radiance Serum",
    badgeColor: "#f59e0b",
  },
  {
    id: "220",
    shopType: "female",
    category: "pcos",
    name: "Gynoveda MyPCOS Ayurvedic Tablets for Delayed & Irregular Periods (120 Tablets)",
    brand: "Gynoveda",
    asin: "B08NDL2T78",
    price: "₹1,499",
    originalPrice: "₹2,200",
    discount: "32% OFF",
    image: "/products/220.jpg",
    tags: ["Kanchnar Guggulu", "Shatapushpa", "Dissolves Ovarian Cysts", "100% Ayurvedic"],
    description: "Formulated by Ayurvedic gynecologists to regulate ovulatory cycles naturally, detoxify uterine tissue, and restore predictable 28-day cycles.",
    badge: "Gynecologist Choice",
    badgeColor: "#8b5cf6",
  },
  {
    id: "221",
    shopType: "female",
    category: "skin",
    name: "Bodywise 2.5% Glutathione Effervescent Tablets with Vitamin C (30 Tablets)",
    brand: "Bodywise",
    asin: "B09BNR6W2X",
    price: "₹999",
    originalPrice: "₹1,499",
    discount: "33% OFF",
    image: "/products/221.jpg",
    tags: ["500mg L-Glutathione", "Melanin Inhibitor", "Fizzy Orange Flavor", "Even Skin Tone"],
    description: "Master intracellular antioxidant that shifts melanin production from dark eumelanin to light pheomelanin, clearing stubborn tanning and melasma.",
    badge: "Skin Brightener",
    badgeColor: "#ec4899",
  },
  {
    id: "222",
    shopType: "female",
    category: "period",
    name: "SOFY AntiBacteria Extra Long Sanitary Pads with Deep Absorbent Core (Pack of 30)",
    brand: "SOFY",
    asin: "B07D3S4X9J",
    price: "₹399",
    originalPrice: "₹499",
    discount: "20% OFF",
    image: "/products/222.jpg",
    tags: ["99.9% Antibacterial Layer", "No Odor Tech", "XXL 320mm Wings", "Heavy Flow Support"],
    description: "Natural green antibacterial sheet prevents 99.9% bacterial proliferation and odor. Ultra-wide back wings guarantee zero overnight side leakage.",
    badge: "Heavy Flow King",
    badgeColor: "#10b981",
  },
  {
    id: "223",
    shopType: "female",
    category: "gear",
    name: "Fitbit Inspire 3 Health & Menstrual Health Tracker Smart Band (Midnight Zen)",
    brand: "Fitbit",
    asin: "B0B3NWV6R6",
    price: "₹6,999",
    originalPrice: "₹8,999",
    discount: "22% OFF",
    image: "/products/223.jpg",
    tags: ["Cycle Phase Tracking", "Sleep Stages", "24/7 Heart Rate", "Water Resistant 50m"],
    description: "Tracks resting heart rate trends, skin temperature fluctuations, and estimated fertile windows to align your workouts with follicular and luteal phases.",
    badge: "Smart Health",
    badgeColor: "#3b82f6",
  },
  {
    id: "224",
    shopType: "female",
    category: "gear",
    name: "Strauss 10mm Extra-Thick Anti-Tear High Density NBR Yoga & Pilates Mat with Strap",
    brand: "Strauss",
    asin: "B00GZ17410",
    price: "₹799",
    originalPrice: "₹1,499",
    discount: "47% OFF",
    image: "/products/224.jpg",
    tags: ["10mm Dense Cushioning", "Knee & Spine Protection", "Non-Slip Ribbed Texture", "Free Carry Strap"],
    description: "Extra thick 10mm cushioning protects sensitive pelvic and knee bones during hip thrusts, core Pilates, and deep restorative yoga stretches.",
    badge: "Joint Cushion",
    badgeColor: "#f59e0b",
  },
];

export const ALL_CATALOG_PRODUCTS = [
  ...COMMON_PRODUCTS,
  ...MALE_PRODUCTS,
  ...FEMALE_PRODUCTS,
];

/**
 * Get product by ID (string or number)
 */
export async function getProductById(id) {
  if (!id) return null;
  const strId = String(id);
  const found = ALL_CATALOG_PRODUCTS.find((p) => String(p.id) === strId);
  if (found) return found;

  // Fallback: Check dynamic Firestore affiliate_products
  try {
    const ref = doc(db, "affiliate_products", strId);
    const snap = await getDoc(ref);
    if (snap.exists()) {
      return { id: snap.id, ...snap.data() };
    }
  } catch (err) {
    console.warn("Error fetching dynamic product:", err);
  }
  return null;
}

// ── USER ORDERS / PURCHASE TRACKING HELPERS ──
const ORDERS_STORAGE_KEY = "ashfitverse_user_orders";

export function getUserOrders() {
  try {
    if (typeof localStorage !== "undefined") {
      const stored = localStorage.getItem(ORDERS_STORAGE_KEY);
      return stored ? JSON.parse(stored) : [];
    }
  } catch {}
  return [];
}

export async function logUserOrder(product, user = null) {
  if (!product) return;

  const orderItem = {
    orderId: `ORD-${Date.now()}-${Math.floor(Math.random() * 1000)}`,
    productId: product.id,
    name: product.name,
    brand: product.brand,
    price: product.price,
    image: product.image,
    asin: product.asin,
    category: product.category,
    shopType: product.shopType || "common",
    timestamp: new Date().toISOString(),
    status: "Ordered via Amazon Prime",
    statusBadgeColor: "#10b981",
  };

  // 1. Save in local cache
  try {
    const existing = getUserOrders();
    // Avoid duplicate within 5 minutes
    const filtered = existing.filter(
      (o) => o.productId !== product.id || Date.now() - new Date(o.timestamp).getTime() > 300000
    );
    const updated = [orderItem, ...filtered];
    localStorage.setItem(ORDERS_STORAGE_KEY, JSON.stringify(updated));
  } catch (err) {
    console.warn("Local orders save error:", err);
  }

  // 2. Sync to Firestore if user is authenticated
  if (user?.uid || user?.email) {
    try {
      await addDoc(collection(db, "user_orders"), {
        ...orderItem,
        uid: user?.uid || null,
        userEmail: user?.email || null,
        userName: user?.name || "Athlete",
        createdAt: serverTimestamp(),
      });
    } catch (err) {
      console.warn("Firestore order log warning:", err);
    }
  }
}
